spring:
  cloud:
    gcp:
      project-id: aflow-491809
      secretmanager:
        enabled: true

  datasource:
    url: jdbc:postgresql://localhost:15432/af_identity
    username: ${DB_USERNAME:assessorflow}
    password: ${DB_PASSWORD:assessorflow_prod}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

logging:
  level:
    sg.edu.nus.iss.identity: DEBUG
    org.hibernate.SQL: DEBUG
